name: build
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      release-tag:
        description: 'Release Tag (v1.x.x)'
        required: true
        type: string
jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-22.04
    env:
      PACKAGE_NAME: luci-app-ssclash
      SDK_URL_PATH: https://downloads.openwrt.org/releases/24.10.2/targets/x86/64/
      SDK_NAME: -sdk-
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -yq gettext libncurses5-dev rsync xsltproc build-essential gawk unzip
      - name: Create Directories
        run: |
          echo "SDK_DL_DIR=$(mktemp -d)" >> $GITHUB_ENV
          echo "SDK_HOME=$(mktemp -d)" >> $GITHUB_ENV
      - name: Prepare Build Environment
        run: |
          cd "$SDK_DL_DIR"
          if ! ( wget -q -O - "$SDK_URL_PATH/sha256sums" | grep -- "$SDK_NAME" > sha256sums.small 2>/dev/null ) ; then
            echo "Can not find ${SDK_NAME} file in sha256sums."
            exit 1
          fi
          SDK_FILE="$(cat sha256sums.small | cut -d' ' -f2 | sed 's/*//g')"
          wget -q -O "$SDK_FILE" "$SDK_URL_PATH/$SDK_FILE"
          if ! sha256sum -c ./sha256sums.small >/dev/null 2>&1 ; then
            echo "SDK can not be verified!"
            exit 1
          fi
          tar --zstd -xf "$SDK_DL_DIR/$SDK_FILE" -C "$SDK_HOME" --strip=1
      - name: Build Packages
        run: |
          cd "$SDK_HOME"
          ./scripts/feeds update > /dev/null 2>&1
          ./scripts/feeds install -a > /dev/null 2>&1
          ln -s "${{ github.workspace }}" "package/$PACKAGE_NAME"
          make defconfig > /dev/null 2>&1
          make package/${PACKAGE_NAME}/compile V=s
          find "$SDK_HOME/bin" -type f -name "${PACKAGE_NAME}_*.ipk" \
           -exec cp -f {} "${{ github.workspace }}" \;
      - name: Generate Release Notes
        run: |
          echo "## Release ${{ github.event.inputs.release-tag }}" > release_notes.md
          echo "" >> release_notes.md
          echo "### Changes" >> release_notes.md
          echo "- Built with OpenWrt SDK 24.10.2" >> release_notes.md
          echo "- Architecture independent package" >> release_notes.md
          echo "- Build date: $(date)" >> release_notes.md
      - name: Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: "*.ipk"
          tag_name: ${{ github.event.inputs.release-tag }}
          body_path: release_notes.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
